# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f18482e398cbb2f9b6ac62021ca6dbf87700b9e7443ec1d855b18dcf8aaddf3307b30e34426d0e33432967e5bae3dcd9a6fb25fa2adc37017f293966b9aed2a9

test:
  secret_key_base: 18aa1bfa6ac6df1b1d9d17e875afe76099b3d088ff61cd3d6c9e415f40eaddc2a0ef3b6753472704d1a8feed6273c0dc2567c832a48bcf379f2e182530097242

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
